export const mockOptimizationData = [
  {
    id: "opt1",
    biddingEntity: "Rest of Search",
    targeting: "",
    campaign: "VC5367 - SPK - HC-O - SPA - Auto 1 Close Match - Y",
    lastOptimized: "Never",
    targetAcos: "30%",
    prioritization: "Balanced",
    currentValue: "40%",
    newValue: "41%",
    delta: "+1.0%",
    changeReason: "Profile Performance",
    limitReason: "",
    currentAcos: "79.6%",
    newAcos: "77.2%",
  },
  {
    id: "opt2",
    biddingEntity: "Rest of Search",
    targeting: "",
    campaign: "VC5367 - SPA - Auto 1 Close Match - Y",
    lastOptimized: "Nov 5, 2024",
    targetAcos: "70%",
    prioritization: "Balanced",
    currentValue: "66%",
    newValue: "33%",
    delta: "-33.0%",
    changeReason: "Optimization Group Perf.",
    limitReason: "Max One Time Decrease",
    currentAcos: "76.8%",
    newAcos: "51.4%",
  },
  {
    id: "opt3",
    biddingEntity: "Product Target",
    targeting: "substitutes",
    campaign: "VC5367 - SPA - Auto 2 Substitutes - Y",
    lastOptimized: "Never",
    targetAcos: "70%",
    prioritization: "Balanced",
    currentValue: "$0.55",
    newValue: "$0.55",
    delta: "0.0%",
    changeReason: "",
    limitReason: "",
    currentAcos: "64.0%",
    newAcos: "64.0%",
  },
  {
    id: "opt4",
    biddingEntity: "Product Target",
    targeting: "close-match",
    campaign: "VC5367 - SPA - Auto 1 Close Match - Y",
    lastOptimized: "Apr 4, 2025",
    targetAcos: "70%",
    prioritization: "Balanced",
    currentValue: "$0.63",
    newValue: "$0.63",
    delta: "0.0%",
    changeReason: "",
    limitReason: "",
    currentAcos: "67.0%",
    newAcos: "67.0%",
  },
  {
    id: "opt5",
    biddingEntity: "Product Pages",
    targeting: "",
    campaign: "VC5367 - SPK - HC-O - SPA - Auto 1 Close Match - Y",
    lastOptimized: "Never",
    targetAcos: "30%",
    prioritization: "Balanced",
    currentValue: "0%",
    newValue: "22%",
    delta: "+22.0%",
    changeReason: "Profile Performance",
    limitReason: "",
    currentAcos: "105.6%",
    newAcos: "82.4%",
  },
  {
    id: "opt6",
    biddingEntity: "Keyword",
    targeting: "baseball sunglasses",
    campaign: "VC5367 - SPK - HC-O - SPA - Auto 1 Close Match - Y",
    lastOptimized: "Never",
    targetAcos: "30%",
    prioritization: "Balanced",
    currentValue: "$0.60",
    newValue: "$0.45",
    delta: "-25.0%",
    changeReason: "High ACOS",
    limitReason: "Max Bid Decrease",
    currentAcos: "96.0%",
    newAcos: "72.0%",
  },
  {
    id: "opt7",
    biddingEntity: "Keyword",
    targeting: "baseball sunglasses",
    campaign: "VC5367 - SPK - HC-O - SPA - Auto 1 Close Match - Y",
    lastOptimized: "Never",
    targetAcos: "30%",
    prioritization: "Balanced",
    currentValue: "$0.95",
    newValue: "$0.71",
    delta: "-25.3%",
    changeReason: "High ACOS",
    limitReason: "Max Bid Decrease",
    currentAcos: "62.0%",
    newAcos: "46.3%",
  },
  {
    id: "opt8",
    biddingEntity: "Rest of Search",
    targeting: "",
    campaign: "VC5367-MBLK-BR-134 - SPA - Auto 1 Close Match - Y",
    lastOptimized: "Nov 5, 2024",
    targetAcos: "60%",
    prioritization: "Balanced",
    currentValue: "85%",
    newValue: "52%",
    delta: "-33.0%",
    changeReason: "Profile Performance",
    limitReason: "Max One Time Decrease",
    currentAcos: "81.0%",
    newAcos: "53.8%",
  },
  {
    id: "opt9",
    biddingEntity: "Product Target",
    targeting: "loose-match",
    campaign: "VC5367-MBLK-BR-134 - SPA - Auto 1 Close Match - Y",
    lastOptimized: "Apr 4, 2025",
    targetAcos: "60%",
    prioritization: "Balanced",
    currentValue: "$0.40",
    newValue: "$0.45",
    delta: "+12.5%",
    changeReason: "High ACOS",
    limitReason: "",
    currentAcos: "52.0%",
    newAcos: "58.5%",
  },
  {
    id: "opt10",
    biddingEntity: "Keyword",
    targeting: "baseball glasses",
    campaign: "VC5367 - SPK - HC-O - SPA - Auto 1 Close Match - Y",
    lastOptimized: "Never",
    targetAcos: "30%",
    prioritization: "Balanced",
    currentValue: "$0.72",
    newValue: "$0.54",
    delta: "-25.0%",
    changeReason: "High ACOS",
    limitReason: "Max Bid Decrease",
    currentAcos: "84.0%",
    newAcos: "63.0%",
  },
  {
    id: "opt11",
    biddingEntity: "Product Target",
    targeting: "loose-match",
    campaign: "VC5367-MWD-WM-134 - SPA - Auto 1 Close Match - Y",
    lastOptimized: "Nov 5, 2024",
    targetAcos: "70%",
    prioritization: "Balanced",
    currentValue: "$0.50",
    newValue: "$0.41",
    delta: "-18.0%",
    changeReason: "High ACOS",
    limitReason: "",
    currentAcos: "88.0%",
    newAcos: "69.6%",
  },
  {
    id: "opt12",
    biddingEntity: "Product Target",
    targeting: "close-match",
    campaign: "VC5367 - SPA - MPM-134 - SPA - Auto 1 Close Match - Y",
    lastOptimized: "Nov 5, 2024",
    targetAcos: "70%",
    prioritization: "Balanced",
    currentValue: "$0.55",
    newValue: "$0.55",
    delta: "0.0%",
    changeReason: "",
    limitReason: "",
    currentAcos: "76.0%",
    newAcos: "76.0%",
  },
  {
    id: "opt13",
    biddingEntity: "Keyword",
    targeting: "sunglasses men",
    campaign: "VC5367 - SPK - HC-O - SPA - Auto 1 Close Match - Y",
    lastOptimized: "Never",
    targetAcos: "30%",
    prioritization: "Balanced",
    currentValue: "$0.53",
    newValue: "$0.40",
    delta: "-24.5%",
    changeReason: "High ACOS",
    limitReason: "Max Bid Decrease",
    currentAcos: "57.0%",
    newAcos: "43.0%",
  },
  {
    id: "opt14",
    biddingEntity: "Product Target",
    targeting: "loose-match",
    campaign: "VC5367 - SPA - Auto 1 Close Match - Y",
    lastOptimized: "Never",
    targetAcos: "70%",
    prioritization: "Balanced",
    currentValue: "$0.47",
    newValue: "$0.47",
    delta: "0.0%",
    changeReason: "",
    limitReason: "",
    currentAcos: "72.0%",
    newAcos: "72.0%",
  },
  {
    id: "opt15",
    biddingEntity: "Rest of Search",
    targeting: "",
    campaign: "VC5367 - SPA - MPM-134 - SPA - Auto 1 Close Match - Y",
    lastOptimized: "Nov 5, 2024",
    targetAcos: "70%",
    prioritization: "Balanced",
    currentValue: "33%",
    newValue: "10%",
    delta: "-23.0%",
    changeReason: "Optimization Group Perf.",
    limitReason: "",
    currentAcos: "79.9%",
    newAcos: "53.5%",
  },
]
